import os
import re

FILE_PATH = r"c:\Users\Kunal\OneDrive\Desktop\Data_axle_logiloop\DATA_AXEL_FINAL\src\routes\app.docs.tsx"

with open(FILE_PATH, 'r', encoding='utf-8') as f:
    content = f.read()

NEW_DOWNLOAD_PPT = """  const downloadPPT = async () => {
    if (!docData) return;
    toast.info("Compiling PPTX file...");
    try {
      const PptxGenJS = (await import("pptxgenjs")).default;
      const pres = new PptxGenJS();
      pres.layout = "LAYOUT_16x9";
      
      const themeColor = "4F46E5"; // Deep Indigo/Purple matching the screenshot
      const bgDark = "0F172A";
      
      const addHeader = (slide: any, title: string) => {
         slide.addShape(pres.ShapeType.rect, { x: 0, y: 0, w: "100%", h: 1.0, fill: { color: themeColor } });
         slide.addText(title, { x: 0.5, y: 0.1, w: "90%", h: 0.8, fontSize: 28, color: "FFFFFF", bold: true });
      };

      // 1. Cover
      let s = pres.addSlide();
      s.background = { fill: bgDark };
      s.addText(docData.projectName || "Food Waste AI", { x: 1, y: 2, w: 8, fontSize: 48, color: "FFFFFF", bold: true, align: "center" });
      s.addText(docData.summary || "The food-waste-ai project aims to reduce food waste...", { x: 1, y: 3.5, w: 8, fontSize: 20, color: "94A3B8", align: "center" });
      s.addText("Generated by AI Document Studio", { x: 1, y: 5.5, w: 8, fontSize: 16, color: themeColor, bold: true, align: "center" });

      // 2. Problem
      s = pres.addSlide();
      addHeader(s, "The Problem");
      s.addText(docData.problem?.statement || "", { x: 0.5, y: 1.5, w: 9, fontSize: 18, color: "333333" });
      docData.problem?.painPoints?.forEach((pt: string, i: number) => {
        s.addText("• " + pt, { x: 0.8, y: 2.8 + (i * 0.6), w: 8.5, fontSize: 16, color: "555555" });
      });

      // 3. Solution
      s = pres.addSlide();
      addHeader(s, "The Solution");
      s.addText(docData.solution?.overview || "", { x: 0.5, y: 1.5, w: 9, fontSize: 18, color: "333333" });
      docData.solution?.keyFeatures?.forEach((f: string, i: number) => {
        const x = i % 2 === 0 ? 0.5 : 5.2;
        const y = 3.0 + Math.floor(i / 2) * 1.2;
        s.addShape(pres.ShapeType.roundRect, { x, y, w: 4.3, h: 0.9, fill: { color: "FFFFFF" }, line: { color: themeColor, width: 1.5 } });
        s.addText(f, { x: x + 0.2, y: y + 0.1, w: 3.9, h: 0.7, fontSize: 14, color: "333333", align: "center" });
      });

      // 4. Technology Stack
      s = pres.addSlide();
      addHeader(s, "Technology Stack");
      const cats = [
        { name: "Frontend", val: docData.techStack?.frontend?.join("\\n• ") },
        { name: "Backend", val: docData.techStack?.backend?.join("\\n• ") },
        { name: "Database", val: docData.techStack?.database?.join("\\n• ") }
      ];
      cats.forEach((c, i) => {
        const x = 0.5 + (i * 3.1);
        s.addText(c.name, { x, y: 1.5, w: 2.8, fontSize: 20, bold: true, color: themeColor });
        s.addText("• " + (c.val || ""), { x, y: 2.2, w: 2.8, fontSize: 16, color: "555555" });
      });

      // 5. System Workflow
      s = pres.addSlide();
      addHeader(s, "System Workflow");
      const steps = ["Upload/Select", "AI Analysis", "Research & Innovation", "Export Documents"];
      steps.forEach((step, i) => {
        s.addShape(pres.ShapeType.rightArrow, { x: 0.5 + (i * 2.3), y: 2.5, w: 2.1, h: 1.2, fill: { color: "FFFFFF" }, line: { color: themeColor, width: 1.5 } });
        s.addText(step, { x: 0.5 + (i * 2.3), y: 2.5, w: 1.8, h: 1.2, fontSize: 14, color: themeColor, bold: true, align: "center" });
      });

      // 6. Architecture
      s = pres.addSlide();
      addHeader(s, "Architecture");
      s.addText(docData.architecture?.description || "", { x: 0.5, y: 1.5, w: 9, fontSize: 18, color: "333333" });
      s.addText("See web view for detailed Mermaid diagram.", { x: 0.5, y: 3.5, w: 9, fontSize: 16, color: "94A3B8", align: "center", italic: true });

      // 7. Conclusion
      s = pres.addSlide();
      addHeader(s, "Conclusion");
      s.addText(docData.results?.impact || "The project delivers significant innovation.", { x: 0.5, y: 2.5, w: 9, fontSize: 24, align: "center", color: themeColor, bold: true });

      pres.writeFile({ fileName: `Presentation_${(docData.projectName||"Project").replace(/\s+/g, "_")}.pptx` });
      toast.success("PPT Downloaded!");
    } catch (e) {
      toast.error("Failed to generate PPT");
      console.error(e);
    }
  };"""

# Replace the downloadPPT function
content = re.sub(
    r'const downloadPPT = async \(\) => \{[\s\S]*?pres\.writeFile\(\{[\s\S]*?toast\.success\("PPT Downloaded!"\);\n\s*\} catch \(e\) \{\n\s*toast\.error\("Failed to generate PPT"\);\n\s*console\.error\(e\);\n\s*\}\n\s*\};',
    NEW_DOWNLOAD_PPT,
    content
)

with open(FILE_PATH, 'w', encoding='utf-8') as f:
    f.write(content)
print("Updated PPT generation to perfectly match the requested single-color theme.")
