/**
 * pdfGenerationService.ts
 * 
 * Generates professional PDFs from documentation and SRS content
 * Uses jsPDF library for PDF creation
 */

import { jsPDF } from 'jspdf';
import { Buffer } from 'buffer';

export interface PDFGenerationOptions {
  title: string;
  subtitle?: string;
  content: string;
  author?: string;
  createdDate?: Date;
  includeTableOfContents?: boolean;
}

/**
 * Generates a professional PDF document from markdown/text content
 * Returns PDF as Buffer
 */
export function generatePDF(options: PDFGenerationOptions): Buffer {
  try {
    const doc = new jsPDF({
      orientation: 'portrait',
      unit: 'mm',
      format: 'a4',
    });

    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const margin = 20;
    const contentWidth = pageWidth - 2 * margin;
    
    let yPosition = margin;
    const lineHeight = 7;
    const fontSize = {
      title: 24,
      heading: 16,
      subheading: 14,
      body: 11,
      small: 9,
    };

    // Helper to add text with auto-wrapping and pagination
    const addWrappedText = (text: string, fontSize: number, options?: any) => {
      doc.setFontSize(fontSize);
      if (options?.bold) doc.setFont('helvetica', 'bold');
      if (options?.color) doc.setTextColor(options.color[0], options.color[1], options.color[2]);

      const lines = doc.splitTextToSize(text, contentWidth);
      const textHeight = lines.length * lineHeight;

      // Check if need new page
      if (yPosition + textHeight > pageHeight - margin) {
        doc.addPage();
        yPosition = margin;
        addFooter();
      }

      doc.text(lines, margin, yPosition);
      yPosition += textHeight + 5;
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(0, 0, 0);
    };

    const addFooter = () => {
      doc.setFontSize(fontSize.small);
      doc.setTextColor(150, 150, 150);
      const pageNum = (doc.internal.pages as any[]).length - 1;
      doc.text(
        `Page ${pageNum}`,
        pageWidth / 2,
        pageHeight - 10,
        { align: 'center' }
      );
    };

    // Cover Page
    yPosition = pageHeight / 2 - 40;
    
    // Title
    addWrappedText(options.title, fontSize.title, { bold: true, color: [0, 102, 204] });
    yPosition += 10;

    // Subtitle
    if (options.subtitle) {
      addWrappedText(options.subtitle, fontSize.subheading);
    }

    // Metadata
    yPosition += 20;
    if (options.author) {
      addWrappedText(`By: ${options.author}`, fontSize.body);
    }
    if (options.createdDate) {
      const dateStr = options.createdDate.toLocaleDateString('en-US', {
        year: 'numeric',
        month: 'long',
        day: 'numeric'
      });
      addWrappedText(`Generated: ${dateStr}`, fontSize.body);
    }

    // New page for content
    doc.addPage();
    yPosition = margin;
    addFooter();

    // Parse and format content
    const lines = options.content.split('\n');
    
    for (const line of lines) {
      const trimmed = line.trim();
      
      if (!trimmed) {
        yPosition += 5;
        continue;
      }

      // Detect headings
      if (trimmed.startsWith('# ')) {
        yPosition += 5;
        addWrappedText(trimmed.replace(/^# /, ''), fontSize.heading, { bold: true });
        yPosition += 3;
      } else if (trimmed.startsWith('## ')) {
        yPosition += 3;
        addWrappedText(trimmed.replace(/^## /, ''), fontSize.subheading, { bold: true, color: [51, 102, 153] });
        yPosition += 2;
      } else if (trimmed.startsWith('### ')) {
        addWrappedText(trimmed.replace(/^### /, ''), fontSize.body, { bold: true });
        yPosition += 1;
      } else if (trimmed.startsWith('- ') || trimmed.startsWith('* ')) {
        // Bullet point
        const bulletText = trimmed.replace(/^[-*]\s/, '');
        addWrappedText('• ' + bulletText, fontSize.body);
      } else {
        // Regular paragraph
        addWrappedText(trimmed, fontSize.body);
      }
    }

    // Add footer to last page
    addFooter();

    // Convert to Buffer
    const pdfBytes = doc.output('arraybuffer');
    return Buffer.from(pdfBytes);
  } catch (error: any) {
    console.error('[PDFGeneration] Error generating PDF:', error.message);
    throw new Error(`Failed to generate PDF: ${error.message}`);
  }
}

/**
 * Generates a comprehensive documentation PDF with cover page, TOC, and formatted content
 */
export function generateDocumentationPDF(
  projectName: string,
  documentation: string,
  author?: string
): Buffer {
  return generatePDF({
    title: `${projectName} - Technical Documentation`,
    subtitle: 'Auto-generated by AI Research Workspace',
    content: documentation,
    author: author || 'AI Research Workspace',
    createdDate: new Date(),
    includeTableOfContents: true,
  });
}

/**
 * Generates a comprehensive SRS PDF with cover page, TOC, and formatted content
 */
export function generateSRSPDF(
  projectName: string,
  srsDocument: string,
  author?: string
): Buffer {
  return generatePDF({
    title: `${projectName} - Software Requirements Specification (SRS)`,
    subtitle: 'IEEE-compliant SRS Document',
    content: srsDocument,
    author: author || 'AI Research Workspace',
    createdDate: new Date(),
    includeTableOfContents: true,
  });
}
