/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppAgentsRouteImport } from './routes/app.agents'
import { Route as AppArchitectureRouteImport } from './routes/app.architecture'
import { Route as AppAssistantRouteImport } from './routes/app.assistant'
import { Route as AppDeepsearchRouteImport } from './routes/app.deepsearch'
import { Route as AppDocsRouteImport } from './routes/app.docs'
import { Route as AppInnovationRouteImport } from './routes/app.innovation'
import { Route as AppKnowledgeRouteImport } from './routes/app.knowledge'
import { Route as AppProjectsRouteImport } from './routes/app.projects'
import { Route as AppResearchRouteImport } from './routes/app.research'
import { Route as AppResourcesRouteImport } from './routes/app.resources'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppVoiceRouteImport } from './routes/app.voice'
import { Route as AppProjectsProjectIdRouteImport } from './routes/app.projects.$projectId'
import { Route as AppWorkflowWorkflowIdRouteImport } from './routes/app.workflow.$workflowId'
import { Route as AppWorkspaceWorkflowIdRouteImport } from './routes/app.workspace.$workflowId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentsRoute = AppAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AppRoute,
} as any)
const AppArchitectureRoute = AppArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => AppRoute,
} as any)
const AppAssistantRoute = AppAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AppRoute,
} as any)
const AppDeepsearchRoute = AppDeepsearchRouteImport.update({
  id: '/deepsearch',
  path: '/deepsearch',
  getParentRoute: () => AppRoute,
} as any)
const AppDocsRoute = AppDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => AppRoute,
} as any)
const AppInnovationRoute = AppInnovationRouteImport.update({
  id: '/innovation',
  path: '/innovation',
  getParentRoute: () => AppRoute,
} as any)
const AppKnowledgeRoute = AppKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppResearchRoute = AppResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => AppRoute,
} as any)
const AppResourcesRoute = AppResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppVoiceRoute = AppVoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsProjectIdRoute = AppProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => AppProjectsRoute,
} as any)
const AppWorkflowWorkflowIdRoute = AppWorkflowWorkflowIdRouteImport.update({
  id: '/workflow/$workflowId',
  path: '/workflow/$workflowId',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkspaceWorkflowIdRoute = AppWorkspaceWorkflowIdRouteImport.update({
  id: '/workspace/$workflowId',
  path: '/workspace/$workflowId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/app/agents': typeof AppAgentsRoute
  '/app/architecture': typeof AppArchitectureRoute
  '/app/assistant': typeof AppAssistantRoute
  '/app/deepsearch': typeof AppDeepsearchRoute
  '/app/docs': typeof AppDocsRoute
  '/app/innovation': typeof AppInnovationRoute
  '/app/knowledge': typeof AppKnowledgeRoute
  '/app/projects': typeof AppProjectsRouteWithChildren
  '/app/research': typeof AppResearchRoute
  '/app/resources': typeof AppResourcesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/voice': typeof AppVoiceRoute
  '/app/': typeof AppIndexRoute
  '/app/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/app/workflow/$workflowId': typeof AppWorkflowWorkflowIdRoute
  '/app/workspace/$workflowId': typeof AppWorkspaceWorkflowIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/app/agents': typeof AppAgentsRoute
  '/app/architecture': typeof AppArchitectureRoute
  '/app/assistant': typeof AppAssistantRoute
  '/app/deepsearch': typeof AppDeepsearchRoute
  '/app/docs': typeof AppDocsRoute
  '/app/innovation': typeof AppInnovationRoute
  '/app/knowledge': typeof AppKnowledgeRoute
  '/app/projects': typeof AppProjectsRouteWithChildren
  '/app/research': typeof AppResearchRoute
  '/app/resources': typeof AppResourcesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/voice': typeof AppVoiceRoute
  '/app': typeof AppIndexRoute
  '/app/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/app/workflow/$workflowId': typeof AppWorkflowWorkflowIdRoute
  '/app/workspace/$workflowId': typeof AppWorkspaceWorkflowIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/app/agents': typeof AppAgentsRoute
  '/app/architecture': typeof AppArchitectureRoute
  '/app/assistant': typeof AppAssistantRoute
  '/app/deepsearch': typeof AppDeepsearchRoute
  '/app/docs': typeof AppDocsRoute
  '/app/innovation': typeof AppInnovationRoute
  '/app/knowledge': typeof AppKnowledgeRoute
  '/app/projects': typeof AppProjectsRouteWithChildren
  '/app/research': typeof AppResearchRoute
  '/app/resources': typeof AppResourcesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/voice': typeof AppVoiceRoute
  '/app/': typeof AppIndexRoute
  '/app/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/app/workflow/$workflowId': typeof AppWorkflowWorkflowIdRoute
  '/app/workspace/$workflowId': typeof AppWorkspaceWorkflowIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/forgot-password'
    | '/signup'
    | '/verify-email'
    | '/app/agents'
    | '/app/architecture'
    | '/app/assistant'
    | '/app/deepsearch'
    | '/app/docs'
    | '/app/innovation'
    | '/app/knowledge'
    | '/app/projects'
    | '/app/research'
    | '/app/resources'
    | '/app/settings'
    | '/app/voice'
    | '/app/'
    | '/app/projects/$projectId'
    | '/app/workflow/$workflowId'
    | '/app/workspace/$workflowId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/signup'
    | '/verify-email'
    | '/app/agents'
    | '/app/architecture'
    | '/app/assistant'
    | '/app/deepsearch'
    | '/app/docs'
    | '/app/innovation'
    | '/app/knowledge'
    | '/app/projects'
    | '/app/research'
    | '/app/resources'
    | '/app/settings'
    | '/app/voice'
    | '/app'
    | '/app/projects/$projectId'
    | '/app/workflow/$workflowId'
    | '/app/workspace/$workflowId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/forgot-password'
    | '/signup'
    | '/verify-email'
    | '/app/agents'
    | '/app/architecture'
    | '/app/assistant'
    | '/app/deepsearch'
    | '/app/docs'
    | '/app/innovation'
    | '/app/knowledge'
    | '/app/projects'
    | '/app/research'
    | '/app/resources'
    | '/app/settings'
    | '/app/voice'
    | '/app/'
    | '/app/projects/$projectId'
    | '/app/workflow/$workflowId'
    | '/app/workspace/$workflowId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  SignupRoute: typeof SignupRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/agents': {
      id: '/app/agents'
      path: '/agents'
      fullPath: '/app/agents'
      preLoaderRoute: typeof AppAgentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/architecture': {
      id: '/app/architecture'
      path: '/architecture'
      fullPath: '/app/architecture'
      preLoaderRoute: typeof AppArchitectureRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/assistant': {
      id: '/app/assistant'
      path: '/assistant'
      fullPath: '/app/assistant'
      preLoaderRoute: typeof AppAssistantRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/deepsearch': {
      id: '/app/deepsearch'
      path: '/deepsearch'
      fullPath: '/app/deepsearch'
      preLoaderRoute: typeof AppDeepsearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/docs': {
      id: '/app/docs'
      path: '/docs'
      fullPath: '/app/docs'
      preLoaderRoute: typeof AppDocsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/innovation': {
      id: '/app/innovation'
      path: '/innovation'
      fullPath: '/app/innovation'
      preLoaderRoute: typeof AppInnovationRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/knowledge': {
      id: '/app/knowledge'
      path: '/knowledge'
      fullPath: '/app/knowledge'
      preLoaderRoute: typeof AppKnowledgeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/projects': {
      id: '/app/projects'
      path: '/projects'
      fullPath: '/app/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/research': {
      id: '/app/research'
      path: '/research'
      fullPath: '/app/research'
      preLoaderRoute: typeof AppResearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/resources': {
      id: '/app/resources'
      path: '/resources'
      fullPath: '/app/resources'
      preLoaderRoute: typeof AppResourcesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/voice': {
      id: '/app/voice'
      path: '/voice'
      fullPath: '/app/voice'
      preLoaderRoute: typeof AppVoiceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/projects/$projectId': {
      id: '/app/projects/$projectId'
      path: '/$projectId'
      fullPath: '/app/projects/$projectId'
      preLoaderRoute: typeof AppProjectsProjectIdRouteImport
      parentRoute: typeof AppProjectsRoute
    }
    '/app/workflow/$workflowId': {
      id: '/app/workflow/$workflowId'
      path: '/workflow/$workflowId'
      fullPath: '/app/workflow/$workflowId'
      preLoaderRoute: typeof AppWorkflowWorkflowIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/workspace/$workflowId': {
      id: '/app/workspace/$workflowId'
      path: '/workspace/$workflowId'
      fullPath: '/app/workspace/$workflowId'
      preLoaderRoute: typeof AppWorkspaceWorkflowIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppProjectsRouteChildren {
  AppProjectsProjectIdRoute: typeof AppProjectsProjectIdRoute
}

const AppProjectsRouteChildren: AppProjectsRouteChildren = {
  AppProjectsProjectIdRoute: AppProjectsProjectIdRoute,
}

const AppProjectsRouteWithChildren = AppProjectsRoute._addFileChildren(
  AppProjectsRouteChildren,
)

interface AppRouteChildren {
  AppAgentsRoute: typeof AppAgentsRoute
  AppArchitectureRoute: typeof AppArchitectureRoute
  AppAssistantRoute: typeof AppAssistantRoute
  AppDeepsearchRoute: typeof AppDeepsearchRoute
  AppDocsRoute: typeof AppDocsRoute
  AppInnovationRoute: typeof AppInnovationRoute
  AppKnowledgeRoute: typeof AppKnowledgeRoute
  AppProjectsRoute: typeof AppProjectsRouteWithChildren
  AppResearchRoute: typeof AppResearchRoute
  AppResourcesRoute: typeof AppResourcesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppVoiceRoute: typeof AppVoiceRoute
  AppIndexRoute: typeof AppIndexRoute
  AppWorkflowWorkflowIdRoute: typeof AppWorkflowWorkflowIdRoute
  AppWorkspaceWorkflowIdRoute: typeof AppWorkspaceWorkflowIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgentsRoute: AppAgentsRoute,
  AppArchitectureRoute: AppArchitectureRoute,
  AppAssistantRoute: AppAssistantRoute,
  AppDeepsearchRoute: AppDeepsearchRoute,
  AppDocsRoute: AppDocsRoute,
  AppInnovationRoute: AppInnovationRoute,
  AppKnowledgeRoute: AppKnowledgeRoute,
  AppProjectsRoute: AppProjectsRouteWithChildren,
  AppResearchRoute: AppResearchRoute,
  AppResourcesRoute: AppResourcesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppVoiceRoute: AppVoiceRoute,
  AppIndexRoute: AppIndexRoute,
  AppWorkflowWorkflowIdRoute: AppWorkflowWorkflowIdRoute,
  AppWorkspaceWorkflowIdRoute: AppWorkspaceWorkflowIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  SignupRoute: SignupRoute,
  VerifyEmailRoute: VerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
